### ISSUE TITLE
Reg checklist - Available Data Sources

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#18]
- [ ] Provide details of all data sources including the experience period for insurance data and when the data was last recorded or updated. (This information can be used to evaluate the completeness of the data source, integrity of the data source, relevance of the data to the predictive timeframe, the potential for historical bias, transparency to insured of the data source, and the ability of the insured to make corrections to the data source.)
- [ ] Specify the companies whose data is included in the datasets. (If the filer is part of a group, do the datasets include data from affiliated companies? If so, which companies? If the filer is an advisory organization, what companies are used? Are the companies included in the data relevant and compatible to the company that filed the rating plan?)
- [ ] Provide the geographical scope and geographic exposure distribution of the data. (Evaluate whether the data is relevant to the loss potential for which it is being used. For example, verify that hurricane data is only used where hurricanes can occur.)
- [ ] List each data source. For each source, list all data elements used as input to the model that came from that source.
- [ ] Specify the type of data (e.g., accident year or policy year, text, numeric).
- [ ] Explain if internal or external data was used and if external data was used, disclose reliance on data supplied by others.
- [ ] Provide details of any non-insurance data used (customer-provided or other), including who owns this data, how consumers can verify their data and correct errors, whether the data was collected by use of a questionnaire/checklist, whether it was voluntarily reported by the applicant, and whether any of the variables are subject to the Fair Credit Reporting Act. If the data is from an outside source, what steps were taken to verify the data was accurate? (If the data is from a third-party source, the company should provide information on how the source addresses the questions in this consideration.)

**Comment by kevinykuo** [comment]
Mentioned in https://github.com/kasaai/pc-pricing-tutorial/pull/40 that dataset includes all insured vehicles in Brazil.
