### ISSUE TITLE
Reg Checklist - Selecting Model Input - Sub-Models

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#19]
- [ ] Disclose reliance on sub-model output used as input to this model. If a sub-model was relied upon, provide the vendor name, and the name and version of the sub-model. If the submodel was built/created in-house, provide contact information for the person responsible for the sub-model. (Examples of such sub-models include credit/financial scoring algorithms and household composite score models. Sub-models can be evaluated separately and in the same manner as the primary model under evaluation.)
- [ ] If using catastrophe model output, identify the vendor and the model settings/assumptions used when the model was run. (For example, it is important to know hurricane model settings for storm surge, demand surge, long/shortterm views.)
- [ ] If using catastrophe model output (a sub-model) as input to the GLM under review, disclose whether loss associated with the modeled output was removed from the loss experience datasets. (If a weather-based sub-model is input to the GLM under review, loss data used to develop the model should not include loss experience associated with the weather-based sub-model. Doing so could cause distortions in the modeled results by double counting such losses when determining relativities or loss loads in the filed rating plan. For example, redundant losses in the data may occur when non-hurricane wind losses are included in the data while also using a severe convective storm model in the actuarial indication. Such redundancy may also occur with the inclusion of fluvial or pluvial flood losses when using a flood model, inclusion of freeze losses when using a winter storm model or including demand surge caused by any catastrophic event.)
- [ ] If using output of any scoring algorithms, provide a list of the variables used to determine the score and provide the source of the data used to calculate the score. (Any sub-model should be reviewed in the same manner as the primary model that uses the submodel’s output as input.)
- [ ] Was the sub-model previously approved (or accepted) by the regulatory agency? (If the sub model was previously approved, that may change the extent of the sub-model’s review.)
