### ISSUE TITLE
Reg Checklist - Selecting Model Input - Adjustments and Scrubbing

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#20]
- [ ] Provide pre-scrubbed data distributions for each input. (Compare with post-scrubbed.)
- [ ] How was missing data handled?
- [ ] If duplicate records exist, how were they handled?
- [ ] Were any data outliers identified and subsequently adjusted? Name the outliers and explain the adjustments made to these outliers.
- [ ] Were premium, exposure, loss or expense data adjusted (e.g., developed, trended, adjusted for catastrophe experience or capped) and, if so, how? Do the adjustments vary for different segments of the data and, if so, what are the segments and how was the data adjusted? (Look for anomalies in the data that should be addressed. For example, is there an extreme loss event in the data? If other processes were used to load rates for specific loss events, those losses should be removed from the input data, e.g., large losses, flood, hurricane or severe convective storm models for PPA comprehensive or homeowners’ loss.)
- [ ] What adjustments were made to raw data, e.g., transformations, binning and/or categorizations? If so, name the characteristic/variable and describe the adjustment.
- [ ] Provide post-scrubbed data distributions for each input.
