### ISSUE TITLE
Reg Checklist - Selecting Model Input - Data Organization

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#21]
- [ ] Document the method of organization for compiling data, including procedures to merge data from different sources and a description of any preliminary analyses, data checks, and logical tests performed on the data and the results of those tests. (This should explain how data from separate sources was merged.)
- [ ] Document the process for reviewing the appropriateness, reasonableness, consistency and comprehensiveness of the data, including a justification of why the data makes sense. (For example, if by-peril modeling is performed, the documentation should be for each peril and make intuitive sense. For example, if “murder” or “theft” rates are used to predict the wind peril, provide support and a logical explanation)
- [ ] Disclose material findings from the data review and identify any potential material limitations, defects, bias or unresolved concerns found or believed to exist in the data.
- [ ] For any errors or material limitations in the data, explain how they were corrected.
