### ISSUE TITLE
Reg Checklist - Building the Model - High-Level Narrative for Building the Model

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#23]
- [ ] Identify the type of model (e.g. Generalized Linear Model – GLM, decision tree, Bayesian Generalized Linear Model, Gradient-Boosting Machine, neural network, etc.), describe its role in the rating system and provide the reasons why that type of model is an appropriate choice for that role. (If by-peril or by-coverage modeling is used, the explanation should be by-peril/coverage.)
- [ ] A description of why the model (using the variables included in it) is appropriate for the line of business. (If by-peril, by-form or by-coverage modeling is used, the explanation should be byperil/coverage/form.)
- [ ] Describe the model review process, from initial concept to final model. Keep this in overview narrative mode, less than 3 pages.
- [ ] Describe whether loss ratio, pure premium or frequency/severity analyses was performed and, if separate frequency/severity modeling was performed, how pure premiums were determined.
- [ ] What is the model’s target variable? (A clear description of the target variable is key to understanding the purpose of the model.)
- [ ] Provide a detailed description of the variable selection process.
- [ ] Was input data segmented in any way,
e.g., was modeling performed on a by coverage or by-peril basis or by-form? Explain the form of data segmentation and the reasons for data segmentation. (The regulator would use this to follow the logic
of the modeling process.)
- [ ] Describe any limitations or concerns in the analysis resulting from data issues and discuss the resulting impact on the modeling results. 
- [ ] How data credibility (or lack thereof) was accounted for in the model building? (Adjustments may be needed given models do not explicitly consider the credibility of the input data or the model’s resulting output; models take input data at face value and assume 100% credibility when producing modeled output.)
