### ISSUE TITLE
Reg Checklist - Building the Model - Medium-Level Narrative for Building the Model

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#24]
- [ ] Describe any judgment used throughout the modeling process. Disclose assumptions used in constructing the model and provide support for these assumptions.
- [ ] If post-model adjustments were made to the data and the model was rerun, explain the details and the rationale. It is not necessary to discuss each iteration of adding and subtracting variables, but the regulator should be provided with a general description of how that was done, including any measures relied upon. (Evaluate the addition or removal of variables and the model fitting.)
- [ ] Describe the univariate testing and balancing that was performed during the model-building process, including a verbal summary of the thought processes involved.
- [ ] Describe the 2-way testing and balancing that was performed during the model-building process, including a verbal summary of the thought processes of including (or not including) interaction terms.
- [ ] For the GLM, what was the link function used? What distribution was used for the model (e.g., Poisson, Gaussian, log-normal, Tweedie)? Explain why the link function distribution was chosen. Provide the formulas for the distribution and link functions, including specific numerical parameters of the distribution.
- [ ] Were there data situations GLM weights were used? Describe these. (Investigate whether identical records were combined to build the model.)
