### ISSUE TITLE
Reg Checklist - Building the Model - Predictor Variables

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#25]
- [ ] Provide the names, descriptions and uses of each predictor variable, offset variable, control variable, proxy variable, geographic variable, geodemographic variable and all other variables in the model; explanations should not use programming language or code. 
- [ ] For each predictor variable, state whether the variable is continuous, discrete or Boolean. 
- [ ] Provide an intuitive argument for why an increase in each predictor variable should increase or decrease frequency, severity, loss costs, expenses, or whatever is being predicted.
- [ ] If the modeler used a Principal Component Analysis (PCA) approach, provide a narrative about that process, explain why PCA was used, and describe the step-by-step process used to transform observations (usually correlated) into a set of linearly uncorrelated variables. Include a listing of the PCA variable and its principal components.
