### ISSUE TITLE
Reg Checklist - Building the Model - Massaging Data, Model Validation and Goodness-of-Fit Measures

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#26]
- [ ] Provide a description of how the available raw data was divided between model development, test and validation datasets. Describe all circumstances under which the testing and validation datasets were accessed.
- [ ] Describe the methods used to assess the statistical significance/goodness of the fit of the model, such as lift charts and statistical tests. Disclose whether the results are based on testing data, validation data and holdout samples. Ensure that the assessment includes model projection results compared to historical actual results to verify that modeled results bear a reasonable relationship to actual results. Discuss the results. (Some states require state-only data to test the plan, especially for analysis where using the state-only data contradicts the countrywide results. State-only data might be more applicable but could also be impacted by low credibility for some segments of risk.)
- [ ] Describe any adjustments that were made in the data with respect to scaling for discrete variables or binning the data.
- [ ] Describe any transformations made for continuous variables.
- [ ] For each discrete variable level, provide the parameter value, confidence intervals, chi-square tests, p-values and any other relevant and material tests. Were model development data, validation data, test data or other data used for these tests? (Typical p-values greater than 5% are large and
should be questioned. Reasonable business judgment can sometimes provide legitimate support for high p-values. Reasonableness of the p-value threshold could also vary depending on the context of the model, e.g., the threshold might be lower when many candidate variables were evaluated for inclusion in the model.)
- [ ] Identify the threshold for statistical significance and explain why it was selected. Provide a verbal defense for keeping the variable for each discrete variable level where the pvalues were not less than the chosen threshold.
- [ ] For overall discrete variables, provide type 3 chi-square tests, pvalues, F tests and any other relevant and material test. Were model development data, validation data, test data or other data used for these tests?
- [ ] For continuous variables, provide confidence intervals, chi-square tests, p-values and any other relevant and material test. Were model development data, validation data, test data or other data used for these tests?
- [ ] Describe how the model was tested for stability over time. (Evaluate the build/test/validation datasets for potential model distortions (e.g., a winter storm in year 3 of 5 can distort the model in both the testing and validation datasets).)
- [ ] Describe how the model was tested for geographic stability, e.g., across states or territories within state. (Evaluate the geographic splits for potential model distortions.)
- [ ] Describe how overfitting was addressed and the results of correlation tests.
- [ ] Provide support demonstrating that the GLM assumptions are appropriate (for example, the choice of error distribution). (Visual review of plots of actual errors is usually sufficient.)
- [ ] Provide the formula relationship between the data and the model outputs, with a definition of each model input and output. Provide all necessary coefficients to evaluate the predicted value for any real or hypothetical set of inputs. (B.4.l and B.4.m will show the mathematical functions involved and could be used to reproduce some model predictions.)
- [ ] Provide 5-10 sample records and the output of the model for those records.
