### ISSUE TITLE
Reg Checklist - Building the Model - “Old Model” Versus “New Model”

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#27]
- [ ] An explanation of why this model is better than the one it is replacing. How was that conclusion formed? What metrics were relied on for measurement? (Regulators should expect to see improvement in the new class plan’s predictive ability or other sufficient reason for the change.)
- [ ] Were 2 Gini coefficients compared? What was the conclusion drawn from this comparison? (One example of a comparison might be sufficient.)
- [ ] Were double lift charts analyzed? What was the conclusion drawn from this analysis?
- [ ] Provide a list of all new predictor variables in the model that were not in the prior model. (Useful to differentiate between old and new variables so the regulator can prioritize more time on factors not yet reviewed.)
- [ ] Provide a list of predictor variables used in the old model that are not used in the new model. Why were they dropped from the new model?
