### ISSUE TITLE
Reg Checklist - Building the Model - Modeler/Software

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#28]
- [ ] Provide the names, contact emails, phone numbers and qualifications of the key persons who:
a. Led the project
b. Compiled the data
c. Built the model
d. Performed peer review
- [ ] What software was used? Provide the name of the software vender/developer, software product and a software version reference.
- [ ] When did work to build the model begin and when was the model build finalized?
