### ISSUE TITLE
Reg Checklist - The Filed Rating Plan - General Impact of Model on Rating Algorithm

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#29]
- [ ] In the Actuarial Memorandum section on the SERFF Supporting Documentation tab, for each model
relied upon, include a document that explains the model and its role in the rating system. (This item becomes “Essential” if the role of the model cannot be immediately discerned by the reviewer from a quick review of the rate and/or rule pages. (Importance is dependent on state requirements and ease of identification by the first layer of review and escalation to the appropriate review staff.))
- [ ] Provide an explanation of how the model was used to adjust the rating algorithm.
- [ ] Provide a complete list of all characteristics/variables used in the proposed rating plan, including those used as input to the model (including sub-models and composite variables) and all other characteristics/variables used to calculate a premium. For each characteristic/variable, indicate if it is only input to the model, whether it is only a separate univariate rating characteristic, or whether it is both input to the model and a separate univariate rating characteristic. The list should provide transparent descriptions of each listed characteristic/variable. (Examples of variables used as inputs to the model and used as separate univariate rating characteristics might be criteria used to determine a rating tier or household composite characteristic.)
- [ ] For each characteristic/variable used as both input to the model (including submodels and composite variables) and as a separate univariate rating characteristic, explain how these are tempered or adjusted to account for possible overlap or redundancy in what the characteristic/variable measures. (Modeling loss ratio with these characteristics/variables as control variables would account for possible overlap. The insurer should address this possibility or other considerations, e.g., tier placement models often use risk characteristics/variables that are also used elsewhere in the rating plan.)
- [ ] If the filing support includes an update or replacement of an existing model, identify and explain the changes in calculations, assumptions, parameters and data used to build the models. Provide an explanation of why the updated/replacement model is better than the one it is replacing, including, how that conclusion was reached, and the metrics relied upon to reach that conclusion.
