### ISSUE TITLE
Data prep

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#3]
As mentioned in https://github.com/kasaai/pc-pricing-tutorial/issues/1#issuecomment-445069800 we'll start with the publicly available Brazilian personal auto data. Since we're focused on building the general pipeline we should ensure it'll be easy to plug in another dataset should we choose to later.

I took a quick look and started documenting findings here: https://github.com/kasaai/pc-pricing-tutorial/blob/master/analysis/data-prep.md

Tasks

- [x] Dictionary for translating column names to English (https://github.com/kasaai/pc-pricing-tutorial/issues/6).
- [x] Translating code descriptions (in the mapping tables) to English, as appropriate (https://github.com/kasaai/pc-pricing-tutorial/issues/6).
- [x] Join the policy table with the mapping tables, so we have meaningful values for all levels (https://github.com/kasaai/pc-pricing-tutorial/issues/7).
- [x] Join the GADM geopackage features to the regions table for visualizations on a map (https://github.com/kasaai/pc-pricing-tutorial/issues/8).

We should be OK working with Portuguese in the factor levels as long as we know what they represent.
