### ISSUE TITLE
Reg Checklist - The Filed Rating Plan - Responses to Data, Credibility and Granularity Issues

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#31]
- [ ] What consideration was given to the credibility of the output data? (At what level of granularity is credibility applied. If modeling was by-coverage, by-form or by-peril, explain how these were handled when there was not enough credible data by coverage, form or peril to model.)
- [ ] If applicable, discuss the rationale for using a model that is more granular than the rating plan. (This is applicable if the insurer had to combine modeled output in order to reduce the granularity of the rating plan.)
- [ ] If applicable, discuss the rationale for using a rating plan that is more granular than modeled output. (A more granular rating plan implies that the insurer had to extrapolate certain rating treatments, especially at the tails of a distribution of attributes, in a manner not specified by the model indications.)
