### ISSUE TITLE
Reg Checklist - The Filed Rating Plan - Consumer Impacts

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/pc-pricing-tutorial#34]
- [ ] Identify model changes and rating variables that will cause large premium disruptions.
- [ ] Did the insurer perform sensitivity testing to identify significant changes in premium due to small or incremental change in a single risk characteristic? If so, discuss and provide the results of that testing. (One way to see sensitivity is to analyze a graph of each risk characteristic’s/variable’s possible relativities. Look for significant variation between adjacent relativities and evaluate if such variation is reasonable.)
- [ ] Measure and describe the impacts on expiring policies and describe the process used by management to mitigate or get comfortable with those impacts.
- [ ] Provide a rate disruption analysis, demonstrating the distribution of percentage impacts on renewal business (create by rerating the current book of business). Include the largest dollar and percentage impacts arising from the filing, including (desirably) the impacts arising specifically from the adoption of the model or changes to the model as they translate into the proposed rating plan. (While the default request would typically be for the distribution of impacts at the overall filing level, the regulator may need to delve into the more granular variable-specific effects of rate changes if there is concern about particular variables having extreme or disproportionate impacts, or significant impacts that have otherwise yet to be substantiated. See Appendix C for an example of a disruption analysis.)
- [ ] Provide exposure distributions for output variables and show the effects of rate changes at granular and summary levels. (See Appendix C for an example of an exposure distribution.)
- [ ] Explain how the insurer will help educate consumers to mitigate their risk.
- [ ] Identify sources to be used at "point of sale" to place individual risks within the matrix of rating system classifications. How can a consumer verify their own "point-of-sale" data and correct any errors? (Could be "Essential" if the variables/characteristics used could 1) have public-policy implications, 2) result in erroneous information being used, or 3) result in many large, disruptive premium changes at renewal. Another consideration to judge “importance” is whether consumers are proactively involved (e.g., use of consumer credit information and credit-report accuracy issues))
- [ ] Identify rating variables that remain static over a consumer’s lifetime versus those that will be updated periodically. Document guidelines for variables that are listed as static yet for which the underlying consumer attributes may change over time. 
- [ ] Provide the regulator with a description of how the company will respond to consumers’ inquiries about how their premium was calculated.
- [ ] Provide the regulator with a means to calculate the rate charged a consumer. (Especially for a complex model or rating plan, a score or premium calculator via Excel or similar means would be ideal, but this could be elicited on a case-by-case basis. Ability to calculate the rate charged can allow the regulator to perform sensitivity testing when there are small changes to a risk characteristic/variable. )
